# Site
repository: dhanrajvermarepo.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Dhanraj Verma
title: Flutter developer
email: dhanrajverma57@gmail.com
cv   : "resume.pdf"
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  dhanrajvermaRepo
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: dhanraj-verma-521601178
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.JPEG
about_content: | # this will include new lines to allow paragraphs
   I am a flutter developer, with experience developing hybrid mobile applications. I am fueled by my passion for understanding new technologies out there. I consider myself a ‘forever student,’ eager to both build on my academic foundations in computer science and technology and stay in tune with the technologies through continued coursework.
   
   I believe mindfulness in the workplace is key to success - a tenet I live out through my interests in yoga, meditation, gardening, and painting. I am currently working as flutter developer.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
   **Interests**
      - Story reading
      - Movies
      - Hill stations
      - Natural sites
      
   **Skills**
      - [Flutter](https://flutter.dev/)
     - [Dart](https://dart.dev/)
     - C, C++
     - jekyll
     - Markdown

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
